export const defaultImages = [
  {
    id: 1,
    size: "XS",
    color: "blue",
    src: "/images/products/fashion/product-1.jpg",
    width: 952,
    height: 1512,
  },
  {
    id: 2,
    size: "S",
    color: "blue",
    src: "/images/products/fashion/product-2.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 3,
    size: "M",
    color: "blue",
    src: "/images/products/fashion/product-3.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 4,
    size: "L",
    color: "blue",
    src: "/images/products/fashion/product-4.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 5,
    size: "L",
    color: "blue",
    src: "/images/products/fashion/product-5.jpg",
    width: 513,
    height: 655,
  },
  {
    id: 6,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-6.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 7,
    size: "M",
    color: "pink",
    src: "/images/products/fashion/product-7.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 8,
    size: "M",
    color: "green",
    src: "/images/products/fashion/product-8.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 9,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-9.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 10,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-10.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 11,
    size: "M",
    color: "white",
    src: "/images/products/fashion/product-11.jpg",
    width: 1080,
    height: 1440,
  },
];

export const defaultImagesForAvailableSlides = [
  {
    src: "/images/products/cosmetic/product-1.jpg",
    size: "XS",
    color: "blue",

    width: 717,
    height: 955,
  },
  {
    src: "/images/products/cosmetic/product-2.jpg",
    size: "S",
    color: "blue",

    width: 717,
    height: 955,
  },
  {
    src: "/images/products/cosmetic/product-3.jpg",
    size: "M",
    color: "blue",

    width: 717,
    height: 955,
  },
  {
    src: "/images/products/cosmetic/product-4.jpg",
    size: "L",
    color: "blue",

    width: 717,
    height: 955,
    extraClass: "swiper-slide-prev",
  },
  {
    src: "/images/products/cosmetic/product-5.jpg",
    size: "L",
    color: "blue",

    width: 759,
    height: 1024,
    extraClass: "swiper-slide-active",
  },
  {
    src: "/images/products/cosmetic/product-6.jpg",
    size: "M",
    color: "gray",

    width: 759,
    height: 1024,
    extraClass: "swiper-slide-next",
  },
  {
    src: "/images/products/cosmetic/product-7.jpg",
    size: "M",
    color: "pink",

    width: 759,
    height: 1024,
  },
  {
    src: "/images/products/cosmetic/product-8.jpg",
    size: "M",
    color: "green",

    width: 759,
    height: 1024,
  },
];

export const defaultImageswithOutofStock = [
  {
    id: 1,
    size: "XS",
    color: "blue",
    src: "/images/products/fashion/product-1.jpg",
    width: 952,
    height: 1512,
    outOfStock: true,
  },
  {
    id: 2,
    size: "S",
    color: "blue",
    src: "/images/products/fashion/product-2.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 3,
    size: "M",
    color: "blue",
    src: "/images/products/fashion/product-3.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 4,
    size: "L",
    color: "blue",
    src: "/images/products/fashion/product-4.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 5,
    size: "L",
    color: "blue",
    src: "/images/products/fashion/product-5.jpg",
    width: 513,
    height: 655,
  },
  {
    id: 6,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-6.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 7,
    size: "M",
    color: "pink",
    src: "/images/products/fashion/product-7.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 8,
    size: "M",
    color: "green",
    src: "/images/products/fashion/product-8.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 9,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-9.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 10,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-10.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 11,
    size: "M",
    color: "white",
    src: "/images/products/fashion/product-11.jpg",
    width: 1080,
    height: 1440,
  },
];
export const defaultImagesWithVideo = [
  {
    id: 1,
    size: "XS",
    color: "blue",
    src: "/images/products/fashion/product-1.jpg",
    width: 952,
    height: 1512,
  },
  {
    id: 2,
    size: "S",
    color: "blue",
    src: "/images/products/fashion/product-2.jpg",
    video: "/images/video/video-product.mp4",
    width: 952,
    height: 1215,
  },
  {
    id: 3,
    size: "M",
    color: "blue",
    src: "/images/products/fashion/product-3.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 4,
    size: "L",
    color: "blue",
    src: "/images/products/fashion/product-4.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 5,
    size: "L",
    color: "blue",
    src: "/images/products/fashion/product-5.jpg",
    width: 513,
    height: 655,
  },
  {
    id: 6,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-6.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 7,
    size: "M",
    color: "pink",
    src: "/images/products/fashion/product-7.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 8,
    size: "M",
    color: "green",
    src: "/images/products/fashion/product-8.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 9,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-9.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 10,
    size: "M",
    color: "gray",
    src: "/images/products/fashion/product-10.jpg",
    width: 952,
    height: 1215,
  },
  {
    id: 11,
    size: "M",
    color: "white",
    src: "/images/products/fashion/product-11.jpg",
    width: 1080,
    height: 1440,
  },
];
