export const testimonials = [
  {
    id: 1,
    delay: "",
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    imgSrc: "/images/products/product-35.jpg",
    imgAlt: "Short Sleeve Office Shirt",
    productName: "Short sleeve office shirt",
    productPrice: "$14,99",
  },
  {
    id: 2,
    delay: "0.1s",
    title: "Dedicated Service",
    text: "“The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally.“",
    author: "Mas Shin",
    imgSrc: "/images/products/product-40.jpg",
    imgAlt: "UrbanCool Work Shirt",
    productName: "UrbanCool Work Shirt",
    productPrice: "$59,99",
  },
  {
    id: 3,
    delay: "0.2s",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Manh Tran",
    imgSrc: "/images/products/product-13.jpg",
    imgAlt: "UrbanCool Work Shirt",
    productName: "WorkMode Lite",
    productPrice: "$39,99",
  },
];

export const testimonialsV2 = [
  {
    id: 4,
    delay: "",
    productImg: "/images/testimonial/tes-1.jpg",
    productAlt: "Image",
    productName: "Sexy lace panties",
    productPrice: "$14,99",
    title: "Dedicated service",
    text: "“ The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally. “",
    author: "Brooklyn Simmons",
  },
  {
    id: 5,
    delay: "0.1s",
    productImg: "/images/testimonial/tes-2.jpg",
    productAlt: "Image",
    productName: "WorkMode Lite",
    productPrice: "$14,99",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Mas Shin",
  },
  {
    id: 6,
    delay: "",
    productImg: "/images/testimonial/tes-1.jpg",
    productAlt: "Image",
    productName: "UrbanCool Work Shirt",
    productPrice: "$14,99",
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Sil Vox",
  },
];

export const testimonialsV01 = [
  {
    id: 7,
    delay: "",
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    imgSrc: "/images/products/product-35.jpg",
    imgAlt: "Short Sleeve Office Shirt",
    productName: "Short sleeve office shirt",
    productPrice: "$14,99",
  },
  {
    id: 8,
    delay: "0.1s",
    title: "Dedicated Service",
    text: "“The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally.“",
    author: "Mas Shin",
    imgSrc: "/images/products/product-40.jpg",
    imgAlt: "UrbanCool Work Shirt",
    productName: "UrbanCool Work Shirt",
    productPrice: "$29,99",
  },
  {
    id: 9,
    delay: "0.2s",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Manh Tran",
    imgSrc: "/images/products/product-13.jpg",
    imgAlt: "UrbanCool Work Shirt",
    productName: "WorkMode Lite",
    productPrice: "$19,99",
  },
  {
    id: 10,
    delay: "",
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    imgSrc: "/images/products/product-35.jpg",
    imgAlt: "Short Sleeve Office Shirt",
    productName: "Short sleeve office shirt",
    productPrice: "$14,99",
  },
];

export const testimonialsV02TypeSpace = [
  {
    id: 11,
    delay: "",
    productImg: "/images/testimonial/tes-3.jpg",
    productAlt: "",
    productName: "Natural Multipurpose Oil",
    productPrice: "$14,99",
    title: "Dedicated service",
    text: "“ The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally. “",
    author: "Brooklyn Simmons",
  },
  {
    id: 12,
    delay: "0.1s",
    productImg: "/images/testimonial/tes-4.jpg",
    productAlt: "",
    productName: "Natural Multipurpose Oil",
    productPrice: "$14,99",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Mas Shin",
  },
  {
    id: 13,
    delay: "",
    productImg: "/images/testimonial/tes-3.jpg",
    productAlt: "",
    productName: "UrbanCool Work Shirt",
    productPrice: "$14,99",
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Sil Vox",
  },
];
export const testimonialsV03 = [
  {
    id: 14,
    title: "Dedicated service",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit enim sit amet nisi tincidunt, in malesuada magna faucibus. Pellentesque eget finibus nunc. Aenean porta aliquam efficitur.",
    author: "Guy Hawkins",
  },
  {
    id: 15,
    title: "Best Product Quality",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus suscipit enim sit amet nisi tincidunt, in malesuada magna faucibus. Pellentesque eget finibus nunc. Aenean porta aliquam efficitur.",
    author: "Mas Shin",
  },
];
export const productThumbs = [
  {
    id: 16,
    imgSrc: "/images/testimonial/thumb-1.jpg",
    imgAlt: "Decorative Dried Flowers",
    title: "Decorative Dried Flowers",
    price: "$69,99",
  },
  {
    id: 17,
    imgSrc: "/images/testimonial/thumb-2.jpg",
    imgAlt: "Decorative Dried Flowers",
    title: "Decorative Dried Flowers",
    price: "$69,99",
  },
];

export const testimonialsJewelry = [
  {
    id: 18,
    delay: "",
    productImg: "/images/products/jewelry/product-5.jpg",
    productAlt: "",
    productName: "Silver Diamond Ring",
    productPrice: "$14,99",
    title: "Dedicated service",
    text: "“ The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally. “",
    author: "Brooklyn Simmons",
  },
  {
    id: 19,
    delay: "0.1s",
    productImg: "/images/products/jewelry/product-9.jpg",
    productAlt: "",
    productName: "Eternity Engagement Ring",
    productPrice: "$19,99",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Mas Shin",
  },
  {
    id: 20,
    delay: "",
    productImg: "/images/products/jewelry/product-5.jpg",
    productAlt: "",
    productName: "UrbanCool Work Shirt",
    productPrice: "$14,99",
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Sil Vox",
  },
];

export const testimonialV04Data = [
  {
    id: 21,
    authorImg: "/images/avatar/avatar-1.jpg",
    title: "Dedicated service",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    productImg: "/images/products/shoes/product-9.jpg",
    productName: "Soft Foam Sneakers",
    productPrice: "$14,99",
  },
  {
    id: 22,
    authorImg: "/images/avatar/avatar-2.jpg",
    title: "Best Product Quality",
    text: "“The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally.“",
    author: "Mas Shin",
    productImg: "/images/products/shoes/product-5.jpg",
    productName: "New Balance 515 V3 Sneaker",
    productPrice: "$14,99",
  },
  {
    id: 23,
    authorImg: "/images/avatar/avatar-3.jpg",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable dependable performance every single time without fail.“",
    author: "Sil Vox",
    productImg: "/images/products/shoes/product-40.jpg",
    productName: "Stretch Running Shoes",
    productPrice: "$14,99",
  },
];

export const testimonialV02Type3Data = [
  {
    id: 24,
    imageSrc: "/images/blog/blog-19.jpg",
    title: "Maui - The courage Chihuahua",
    price: "$14,99",
    text: "“ The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally. “",
    author: "Brooklyn Simmons",
  },
  {
    id: 25,
    imageSrc: "/images/blog/blog-20.jpg",
    title: "The Let Them Theory",
    price: "$39,99",
    text: "“No surprises, just consistent and dependable performance every single time without fail. “",
    author: "Mas Shin",
  },
  {
    id: 26,
    imageSrc: "/images/blog/blog-19.jpg",
    title: "Maui - The courage Chihuahua",
    price: "$14,99",
    text: "“ The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally. “",
    author: "Xil Vo",
  },
];

export const testimonialV01Data = [
  {
    id: 27,
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    imageSrc: "/images/products/medical/product-21.jpg",
    productName: "Biotin 10,000 mcg Supplement",
    price: "$14,99",
    delay: "",
  },
  {
    id: 28,
    title: "Dedicated Service",
    text: "“The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally.“",
    author: "Mas Shin",
    imageSrc: "/images/products/medical/product-22.jpg",
    productName: "Organic Comfrey Oil Raw",
    price: "$29,99",
    delay: "0.1s",
  },
  {
    id: 29,
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Manh Tran",
    imageSrc: "/images/products/medical/product-23.jpg",
    productName: "Pure Body Naturals Anti",
    price: "$19,99",
    delay: "0.2s",
  },
  {
    id: 30,
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    imageSrc: "/images/products/medical/product-21.jpg",
    productName: "Biotin 10,000 mcg Supplement",
    price: "$14,99",
    delay: "",
  },
];

export const gymTestimonials = [
  {
    id: 31,
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    imageSrc: "/images/products/gym/product-3.jpg",
    imageAlt: "Breathable workout gloves",
    productName: "Breathable workout gloves",
    price: "$14,99",
  },
  {
    id: 32,
    title: "Dedicated Service",
    text: "“The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally.“",
    author: "Mas Shin",
    imageSrc: "/images/products/gym/product-19.jpg",
    imageAlt: "Adidas Unisex Sports Bag",
    productName: "Adidas Unisex Sports Bag",
    price: "$29,99",
  },
  {
    id: 33,
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Manh Tran",
    imageSrc: "/images/products/gym/product-7.jpg",
    imageAlt: "Protein Powder",
    productName: "Protein Powder",
    price: "$19,99",
  },
  {
    id: 34,
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    imageSrc: "/images/products/gym/product-3.jpg",
    imageAlt: "Breathable workout gloves",
    productName: "Breathable workout gloves",
    price: "$14,99",
  },
];

export const testimonialV02Data = [
  {
    id: 35,
    imageSrc: "/images/testimonial/tes-5.jpg",
    imageAlt: "Multicolored stone bracelet",
    productName: "Multicolored stone bracelet",
    price: "$14,99",
    title: "Dedicated service",
    text: "“ The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally. “",
    author: "Brooklyn Simmons",
    delay: "", // No delay for first and third
  },
  {
    id: 36,
    imageSrc: "/images/testimonial/tes-6.jpg",
    imageAlt: "Hand knitted beanie",
    productName: "Hand knitted beanie",
    price: "$14,99",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Mas Shin",
    delay: "0.1s",
  },
  {
    id: 37,
    imageSrc: "/images/testimonial/tes-5.jpg",
    imageAlt: "Multicolored stone bracelet",
    productName: "Multicolored stone bracelet",
    price: "$14,99",
    title: "Dedicated service",
    text: "“ The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally. “",
    author: "Brooklyn Simmons",
    delay: "",
  },
];

export const testimonialV01Data2 = [
  {
    id: 38,
    delay: "",
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    productImg: "/images/products/watch/product-1.jpg",
    productAlt: "Men's Office Watches",
    productName: "Men's Office Watches",
    productPrice: "$14,99",
  },
  {
    id: 39,
    delay: "0.1s",
    title: "Dedicated Service",
    text: "“The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally.“",
    author: "Mas Shin",
    productImg: "/images/products/watch/product-5.jpg",
    productAlt: "Waterproof Watch",
    productName: "Waterproof Watch",
    productPrice: "$29,99",
  },
  {
    id: 40,
    delay: "0.2s",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable performance every single time without fail.“",
    author: "Manh Tran",
    productImg: "/images/products/watch/product-15.jpg",
    productAlt: "Sapphire Glass Watch",
    productName: "Sapphire Glass Watch",
    productPrice: "$19,99",
  },
  // Duplicate of item 1
  {
    id: 41,
    delay: "",
    title: "Best Product Quality",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    productImg: "/images/products/watch/product-1.jpg",
    productAlt: "Men's Office Watches",
    productName: "Men's Office Watches",
    productPrice: "$14,99",
  },
];

export const testimonialV04Data3 = [
  {
    id: 42,
    avatar: "/images/avatar/avatar-1.jpg",
    title: "Dedicated service",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    productImage: "/images/products/car-auto/product-1.jpg",
    productAlt: "Cluth",
    productName: "6DCT250 Transmission Clutch",
    productPrice: "$14,99",
  },
  {
    id: 43,
    avatar: "/images/avatar/avatar-2.jpg",
    title: "Best Product Quality",
    text: "“The support from ACIS has been outstanding. Anytime we had a question or needed help, their team responded quickly and professionally.“",
    author: "Mas Shin",
    productImage: "/images/products/car-auto/product-9.jpg",
    productAlt: "Wheel",
    productName: "Pilot Wheel Covers",
    productPrice: "$14,99",
  },
  {
    id: 44,
    avatar: "/images/avatar/avatar-3.jpg",
    title: "Exceptional Reliability",
    text: "“No surprises, just consistent and dependable dependable performance every single time without fail.“",
    author: "Sil Vox",
    productImage: "/images/products/car-auto/product-3.jpg",
    productAlt: "Short Sleeve Office Shirt",
    productName: "Front Brake Kit",
    productPrice: "$14,99",
  },
  // Duplicate of item 1
  {
    id: 45,
    avatar: "/images/avatar/avatar-1.jpg",
    title: "Dedicated service",
    text: "“The build quality is excellent and everything works smoothly. I can feel the difference compared to other brands“",
    author: "Brooklyn Simmons",
    productImage: "/images/products/car-auto/product-1.jpg",
    productAlt: "Cluth",
    productName: "6DCT250 Transmission Clutch",
    productPrice: "$14,99",
  },
];

export const testimonialData = [
  {
    id: 46,
    name: "Brooklyn Simmons",
    avatar: "/images/avatar/avatar-1.jpg",
    text: `“ Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce malesuada nulla a diam tempus mattis ut at odio. Nam pharetra et sapien posuere placerat. Sed vitae rhoncus nibh. Phasellus suscipit vitae lorem vel pretium “`,
  },
  {
    id: 47,
    name: "Mas Shin",
    avatar: "/images/avatar/avatar-2.jpg",
    text: `“Our experience with ACIS has been excellent. Their support team is always quick to respond and very professional. They handle all questions and issues with great care and efficiency, making them a reliable partner we truly appreciate.“`,
  },
  {
    id: 48,
    name: "Sil Vox",
    avatar: "/images/avatar/avatar-3.jpg",
    text: `“ACIS consistently provides fast, professional support whenever we need it. Their team is knowledgeable and always ready to help with any issue, big or small. We really appreciate their reliable partnership.“`,
  },
];
